language: node_js
node_js:
- '8'
branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_060e78cb4771_key -iv $encrypted_060e78cb4771_iv
  -in id_rsa.enc -out .travis/id_rsa -d
# - openssl aes-256-cbc -K $encrypted_060e78cb4771_key -iv $encrypted_060e78cb4771_iv
#   -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 .travis/id_rsa
- eval $(ssh-agent)
- sudo ssh-add .travis/id_rsa
# - ssh -T git@github.com
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'dongsuo'
- git config --global user.email xuxiaofei1.0@outlook.com
- sudo rm -rf .deploy_git
install:
- npm install hexo-cli -g
- LIBSASS_EXT="no" npm install
script:
- hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Deploy blog pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/dongsuo/blog" gh-page
