# 配置语言及相应版本
language: node_js

node_js:
  - "8"
# 项目所在分支
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_060e78cb4771_key -iv $encrypted_060e78cb4771_iv
  -in id_rsa.enc -out .travis/id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa 
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'acwong'
- git config --global user.email acwong00@gmail.com

# 安装依赖
install:
- npm install hexo-cli -g
- npm install

# 部署的命令
script:
- npm run deploy  # hexo clean && hexo g -d
# .travis.yml 缓存
cache:
  directories:
    - node_modules
