menu:
    Home: https://islasher.com
    VisLib: https://vislib.best
    Blog: /
    Archive: /archives/
    About: /about/

favicon: /logo.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
google_analytics: UA-110850031-1
ga: UA-110850031-1
