menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/dongsuo
    ZhiHu: https://www.zhihu.com/people/xu-xiao-fei-63

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
google-analytics:
ga: UA-110850031-1

# Copyright Infomation
startyear: 2016
